// ============================================================
// PRODUCTS DATABASE - ADD YOUR PRODUCTS HERE
// To add a product: copy one object and fill in your details
// For images: put your photo in src/assets/ and use the path
// ============================================================

export const categories = [
  { id: 'all', label: 'Te gjitha', icon: '🔍' },
  { id: 'cctv', label: 'CCTV Systems', icon: '📹' },
  { id: 'smarthome', label: 'Smart Home', icon: '🏠' },
  { id: 'audio', label: 'Audio Systems', icon: '🔊' },
  { id: 'it', label: 'IT & Network', icon: '💻' },
  { id: 'access', label: 'Access Control', icon: '🔐' },
  { id: 'alarm', label: 'Alarm Systems', icon: '🚨' },
  { id: 'cables', label: 'Kabllo & Aksesore', icon: '🔌' },
]

export const products = [
  // ─── CCTV ───────────────────────────────────────────────
  {
    id: 1,
    name: 'Kamera IP 4MP Outdoor',
    category: 'cctv',
    brand: 'Dahua',
    model: 'IPC-HFW2449S',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Bestseller',
    badgeColor: '#e8ff00',
    specs: ['4MP Super HD', 'IR 30m Night Vision', 'IP67 Waterproof', 'H.265+'],
    desc: 'Kamera e jashtme profesionale me rezolucion 4MP, night vision 30m dhe mbrojtje IP67 ndaj motit.',
    inStock: true,
  },
  {
    id: 2,
    name: 'NVR 8 Kanale 4K',
    category: 'cctv',
    brand: 'Dahua',
    model: 'NVR2108HS-8P-I',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['8 Kanale', '4K Output', 'PoE Built-in', '2TB HDD'],
    desc: 'Recorder profesional 8 kanale me PoE te integruar. Perfekt per sisteme CCTV te mesme.',
    inStock: true,
  },
  {
    id: 3,
    name: 'Kamera PTZ 2MP',
    category: 'cctv',
    brand: 'Hikvision',
    model: 'DS-2DE4A425IWG-E',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Pro',
    badgeColor: '#00d4ff',
    specs: ['2MP Full HD', 'Zoom 25x Optik', 'Pan/Tilt/Zoom', 'IR 100m'],
    desc: 'Kamera PTZ me zoom 25x optik, ideale per monitorim te hapesirave te gjera.',
    inStock: true,
  },
  {
    id: 4,
    name: 'Paketa 4 Kamera + NVR',
    category: 'cctv',
    brand: 'Dahua',
    model: 'KIT-4CAM',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Paket',
    badgeColor: '#a855f7',
    specs: ['4x Kamera 4MP', '1x NVR 4 Kanale', '1TB HDD', 'Instalim i perfshire'],
    desc: 'Paket komplet per shtepie ose biznes te vogel. Gati per instalim me te gjitha kabllot.',
    inStock: true,
  },
  {
    id: 5,
    name: 'Paketa 8 Kamera + NVR',
    category: 'cctv',
    brand: 'Dahua',
    model: 'KIT-8CAM',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Bestseller',
    badgeColor: '#e8ff00',
    specs: ['8x Kamera 4MP', '1x NVR 8 Kanale', '2TB HDD', 'Instalim i perfshire'],
    desc: 'Paketa me e popullarizuar per biznese dhe ambiente komerciale.',
    inStock: true,
  },
  {
    id: 6,
    name: 'Kamera Indoor 2MP WiFi',
    category: 'cctv',
    brand: 'EZVIZ',
    model: 'C6N',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['2MP Full HD', 'WiFi', '360 Pan/Tilt', 'Two-way Audio'],
    desc: 'Kamera e brendshme me WiFi dhe levizje 360 grade. Kontrollo nga telefoni.',
    inStock: true,
  },

  // ─── SMART HOME ──────────────────────────────────────────
  {
    id: 7,
    name: 'Smart Switch 2 Gang',
    category: 'smarthome',
    brand: 'Tuya',
    model: 'TS0002',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['WiFi Control', 'Voice Control', 'App Remote', 'Timer'],
    desc: 'Celes inteligjent me kontroll nga aplikacioni. Kompatibel me Alexa dhe Google Home.',
    inStock: true,
  },
  {
    id: 8,
    name: 'Smart Home Hub Starter Kit',
    category: 'smarthome',
    brand: 'Tuya',
    model: 'HUB-KIT-S',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Rekomanduar',
    badgeColor: '#e8ff00',
    specs: ['Hub Central', '4x Smart Switch', '2x Sensor', 'App Setup'],
    desc: 'Kit fillestar per smart home. Perfekt per te filluar automatizimin e shtepise.',
    inStock: true,
  },
  {
    id: 9,
    name: 'Smart Bulb RGB E27',
    category: 'smarthome',
    brand: 'Philips Hue',
    model: 'E27-RGB',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['16M Ngjyra', 'WiFi + BT', 'Dimmer', 'App Control'],
    desc: 'Llamba inteligjente me 16 milion ngjyra. Krijo atmosferen perfekte me nje klikim.',
    inStock: true,
  },

  // ─── AUDIO ───────────────────────────────────────────────
  {
    id: 10,
    name: 'Amplifikator 2x100W',
    category: 'audio',
    brand: 'Apart',
    model: 'CHAMP2',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['2x 100W RMS', 'Class D', 'Stereo/Bridge', 'Rack Mount'],
    desc: 'Amplifikator profesional stereo per ambiente komerciale dhe biznese.',
    inStock: true,
  },
  {
    id: 11,
    name: 'Altoparlant Tavani 6"',
    category: 'audio',
    brand: 'Apart',
    model: 'CM6T',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['6 inch', '100V Line', '16W', 'Ceiling Mount'],
    desc: 'Altoparlant per tavane, ideal per restorante, hotele dhe zyra.',
    inStock: true,
  },
  {
    id: 12,
    name: 'Sistem PA Komplet',
    category: 'audio',
    brand: 'Apart',
    model: 'PA-KIT-PRO',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Pro',
    badgeColor: '#ff6b35',
    specs: ['Mixer 4 kanale', '2x Amplifikator', '6x Altoparlant', 'Instalim i perfshire'],
    desc: 'Sistem audio i plote per ambiente komerciale. Ideal per hotele, restorante dhe dyqane.',
    inStock: true,
  },

  // ─── IT & NETWORK ─────────────────────────────────────────
  {
    id: 13,
    name: 'Router WiFi 6 AX3000',
    category: 'it',
    brand: 'TP-Link',
    model: 'Archer AX55',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['WiFi 6', 'AX3000', 'MU-MIMO', '4x LAN Gigabit'],
    desc: 'Router me teknologjine me te re WiFi 6. Perfekt per shtepie dhe zyra te mesme.',
    inStock: true,
  },
  {
    id: 14,
    name: 'Switch PoE 8 Port',
    category: 'it',
    brand: 'Ubiquiti',
    model: 'USW-Lite-8-PoE',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Pro',
    badgeColor: '#00d4ff',
    specs: ['8x Port Gigabit', '4x PoE+', '52W PoE Budget', 'Managed'],
    desc: 'Switch profesional me PoE per ushqim te kamerave dhe access point pa kabllo energjie.',
    inStock: true,
  },
  {
    id: 15,
    name: 'Access Point WiFi 6',
    category: 'it',
    brand: 'Ubiquiti',
    model: 'U6-Lite',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['WiFi 6', 'AX1500', 'PoE Powered', '300+ Clients'],
    desc: 'Access point profesional per mbulim WiFi te qendrueshme ne zyra dhe hotele.',
    inStock: true,
  },

  // ─── ACCESS CONTROL ───────────────────────────────────────
  {
    id: 16,
    name: 'Kontroll Aksesi RFID',
    category: 'access',
    brand: 'ZKTeco',
    model: 'C3-100',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['RFID Card', '1000 Perdorues', 'TCP/IP', 'Software i perfshire'],
    desc: 'Sistem aksesi me karte RFID. Perfekt per zyra dhe biznese me staf te shumte.',
    inStock: true,
  },
  {
    id: 17,
    name: 'Smart Lock Biometrik',
    category: 'access',
    brand: 'ZKTeco',
    model: 'AL20B',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Smart',
    badgeColor: '#a855f7',
    specs: ['Fingerprint', 'RFID Card', 'PIN Code', 'App Control'],
    desc: 'Brava inteligjente me gjurme gishti, karte dhe PIN. Hapje nga aplikacioni.',
    inStock: true,
  },

  // ─── ALARM ───────────────────────────────────────────────
  {
    id: 18,
    name: 'Panele Alarmi Wireless',
    category: 'alarm',
    brand: 'Ajax',
    model: 'Hub 2 Plus',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: 'Premium',
    badgeColor: '#e8ff00',
    specs: ['Wireless', '4G + WiFi + Ethernet', '150 Devices', 'App Control'],
    desc: 'Panele alarmi profesional wireless me lidhje 4G. Njoftimet ne telefon ne kohe reale.',
    inStock: true,
  },
  {
    id: 19,
    name: 'Sensor Levizje PIR',
    category: 'alarm',
    brand: 'Ajax',
    model: 'MotionProtect',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['Wireless', '12m Range', '90deg Detection', 'Pet Immunity'],
    desc: 'Sensor levizje wireless me imunitet ndaj kafsheve shtepiak deri 20kg.',
    inStock: true,
  },

  // ─── CABLES ──────────────────────────────────────────────
  {
    id: 20,
    name: 'Kabllo UTP Cat6 305m',
    category: 'cables',
    brand: 'Belden',
    model: 'CAT6-305',
    price: null,
    priceLabel: 'Kerko Cmimin',
    image: null,
    badge: null,
    specs: ['Cat6', '305m Roll', 'Gigabit', 'Indoor/Outdoor'],
    desc: 'Kabllo rrjeti Cat6 cilesi e larte per instalime profesionale.',
    inStock: true,
  },
]
